version: 2.16.1
slug: openthread_border_router_2
name: OpenThread Border Router 2
description: OpenThread Border Router add-on - Instance 2
url: >-
  https://github.com/LeGoFiN/ha_addons/tree/master/openthread_border_router_2
arch:
  - aarch64
  - amd64
homeassistant: 2025.7.0
gpio: true
hassio_api: true
discovery:
  - otbr
# IPC is only used within the Add-on
host_ipc: false
host_network: true
host_uts: true
privileged:
  - IPC_LOCK
  - NET_ADMIN
devices:
  - /dev/net/tun
image: homeassistant/{arch}-addon-otbr
init: false
options:
  device: null
  baudrate: "460800"
  flow_control: true
  otbr_log_level: notice
  firewall: true
  nat64: false
  beta: false
ports:
  8082/tcp: 8082
  8083/tcp: null
ports_description:
  8082/tcp: OpenThread REST API port (Instance 2)
  8083/tcp: OpenThread Web port (Instance 2)
schema:
  device: device(subsystem=tty)
  baudrate: list(57600|115200|230400|460800|921600|1000000)
  flow_control: bool
  network_device: str?
  otbr_log_level: list(debug|info|notice|warning|error|critical|alert|emergency)
  firewall: bool
  nat64: bool
  beta: bool?
startup: services
